[package]
name = "balance-toolkit-app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "balance_toolkit_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.28" }
anyhow = "1.0"
futures = "0.3"
hidapi = "2.6.3"
env_logger = "0.11"
log = "0.4"

[target.'cfg(target_os = "linux")'.dependencies]
bluer = { version = "0.17.3", features = ["bluetoothd"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.60.0", features = [
  "Devices_Bluetooth",
  "Devices_Enumeration",
  "Foundation_Collections",
] }
windows-future = "0.1.0"

