[package]
name = "the-balance-toolkitapp"
description = "A Toolkit to perform operations with a Nintendo Wii Balance Board"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
toolkit-core.workspace = true
anyhow.workspace = true
log.workspace = true
serde.workspace = true
tauri = { version = "2.11.5", features = ["unstable"] }
tauri-plugin-dialog = "2.7.3"
tauri-plugin-fs = "2.5.2"
tauri-plugin-opener = "2.5.5"
tokio.workspace = true
