// @ts-nocheck
// Generated by tauri-specta from apps/tauri/src-tauri/src/frontend/tauri.rs. Do not edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	settingsGetSettings: () => __TAURI_INVOKE<GeneralSettings>("settings_get_settings").then((v) => (({...v,processingSettings:({...v.processingSettings,baselineWeight:v.processingSettings.baselineWeight==null?v.processingSettings.baselineWeight:v.processingSettings.baselineWeight})}) as typeof v)),
	settingsSetSettings: (settings: GeneralSettings) => __TAURI_INVOKE<null>("settings_set_settings", { settings: ({...settings,processingSettings:({...settings.processingSettings,baselineWeight:settings.processingSettings.baselineWeight==null?settings.processingSettings.baselineWeight:settings.processingSettings.baselineWeight})}) }),
	userPageInformation: () => __TAURI_INVOKE<UserPageInformation>("user_page_information").then((v) => (({...v,users:v.users.map(i=>({...i,height:i.height==null?i.height:i.height,weight:i.weight==null?i.weight:i.weight}))}) as typeof v)),
	userSelectUser: (userId: number) => __TAURI_INVOKE<null>("user_select_user", { userId }),
	userCreate: () => __TAURI_INVOKE<User>("user_create").then((v) => (({...v,height:v.height==null?v.height:v.height,weight:v.weight==null?v.weight:v.weight}) as typeof v)),
	userUpdate: (user: User) => __TAURI_INVOKE<null>("user_update", { user: ({...user,height:user.height==null?user.height:user.height,weight:user.weight==null?user.weight:user.weight}) }),
	userDelete: (userId: number) => __TAURI_INVOKE<null>("user_delete", { userId }),
	userMeasureWeight: (channel: Channel<number | null>, macAddress: number, measurementId: string) => __TAURI_INVOKE<null>("user_measure_weight", { channel, macAddress, measurementId }),
	userStopMeasureWeight: (measurementId: string) => __TAURI_INVOKE<null>("user_stop_measure_weight", { measurementId }),
	devicesGetSelectedDevices: () => __TAURI_INVOKE<number[]>("devices_get_selected_devices"),
	devicesFetchAllDevices: () => __TAURI_INVOKE<NintendoDevice[]>("devices_fetch_all_devices"),
	devicesScanWithoutTimeout: () => __TAURI_INVOKE<null>("devices_scan_without_timeout"),
	devicesCancelScan: () => __TAURI_INVOKE<null>("devices_cancel_scan"),
	devicesIsScanning: () => __TAURI_INVOKE<boolean>("devices_is_scanning"),
	devicesSelectDevice: (macAddress: number) => __TAURI_INVOKE<null>("devices_select_device", { macAddress }),
	devicesUnselectDevice: (macAddress: number) => __TAURI_INVOKE<null>("devices_unselect_device", { macAddress }),
	devicesUpdateDeviceName: (macAddress: number, deviceName: string) => __TAURI_INVOKE<null>("devices_update_device_name", { macAddress, deviceName }),
	devicesRemoveDevice: (macAddress: number) => __TAURI_INVOKE<null>("devices_remove_device", { macAddress }),
	devicesIdentifyDevice: (macAddress: number) => __TAURI_INVOKE<null>("devices_identify_device", { macAddress }),
	devicesTareDevice: (macAddress: number) => __TAURI_INVOKE<null>("devices_tare_device", { macAddress }),
	devicesStartCalibrationStream: (macAddress: number, calibrationChannel: Channel<FrontendCalibrationReading>) => __TAURI_INVOKE<null>("devices_start_calibration_stream", { macAddress, calibrationChannel }),
	devicesStopCalibrationStream: (macAddress: number) => __TAURI_INVOKE<null>("devices_stop_calibration_stream", { macAddress }),
	devicesSubmitCalibration: (macAddress: number, weightKg: number, readings: CapturedCalibrationReading[]) => __TAURI_INVOKE<DeviceCalibrationData>("devices_submit_calibration", { macAddress, weightKg, readings }).then((v) => (({...v,positions:Object.fromEntries(Object.entries(v.positions).map(([k,v])=>[k,v]))}) as typeof v)),
	sessionStartSession: (sessionChannel: Channel<FrontendBalanceBoardEvent>) => __TAURI_INVOKE<null>("session_start_session", { sessionChannel }),
	sessionStopSession: () => __TAURI_INVOKE<null>("session_stop_session"),
	sessionInformation: () => __TAURI_INVOKE<SessionInformation>("session_information"),
	sessionUpdateSessionConfiguration: (configuration: SessionSettings) => __TAURI_INVOKE<null>("session_update_session_configuration", { configuration }),
	/**
	 *  Everything the activity popup needs: the activity, the current block and the time
	 *  until the next one.
	 */
	sessionActivityState: () => __TAURI_INVOKE<{
	activity: Activity,
	ongoingState: OngoingSessionActivityState | null,
} | null>("session_activity_state"),
	sessionTareDevices: () => __TAURI_INVOKE<null>("session_tare_devices"),
	replayStartReplay: (sessionChannel: Channel<FrontendBalanceBoardEvent>) => __TAURI_INVOKE<null>("replay_start_replay", { sessionChannel }),
	replayStopReplay: () => __TAURI_INVOKE<null>("replay_stop_replay"),
	replayInformation: () => __TAURI_INVOKE<{
	user: User,
	core: SessionSettings,
	devices: SelectedBoard[],
	activity: Activity | null,
	filePath: string,
	hasOngoingSession: boolean,
} | null>("replay_information").then((v) => (v==null?v:({...v,user:({...v.user,height:v.user.height==null?v.user.height:v.user.height,weight:v.user.weight==null?v.user.weight:v.user.weight})}) as typeof v)),
	replayUpdate: (configuration: SessionSettings) => __TAURI_INVOKE<null>("replay_update", { configuration }),
	replayLoadFile: (filePath: string) => __TAURI_INVOKE<null>("replay_load_file", { filePath }),
	replayClearReplay: () => __TAURI_INVOKE<null>("replay_clear_replay"),
	replayLoadLastSessionInfo: () => __TAURI_INVOKE<{
	user: User,
	sessionStats: SessionStats,
	fileLocation: string,
	activity: Activity | null,
} | null>("replay_load_last_session_info").then((v) => (v==null?v:({...v,user:({...v.user,height:v.user.height==null?v.user.height:v.user.height,weight:v.user.weight==null?v.user.weight:v.user.weight})}) as typeof v)),
	activityGetAvailableTimeBlocks: () => __TAURI_INVOKE<TimelineBlock[]>("activity_get_available_time_blocks"),
	activityGetActivities: () => __TAURI_INVOKE<Activity[]>("activity_get_activities"),
	activityGetActivity: (activityId: string) => __TAURI_INVOKE<Activity>("activity_get_activity", { activityId }),
	activityUpdateActivity: (activity: Activity) => __TAURI_INVOKE<null>("activity_update_activity", { activity }),
	activityResetActivityToDefault: (activityId: string) => __TAURI_INVOKE<Activity>("activity_reset_activity_to_default", { activityId }),
};

/** Events */
export const events = {
	boardDisconnected: makeEvent<BoardDisconnected>("board-disconnected"),
	newBoard: makeEvent<NewBoard>("new-board"),
	replayCompleted: makeEvent<ReplayCompleted>("replay-completed"),
	sessionActivityChanged: makeEvent<SessionActivityChanged>("session-activity-changed"),
	sessionCompleted: makeEvent<SessionCompleted>("session-completed"),
	sessionStarted: makeEvent<SessionStarted>("session-started"),
};

/* Types */
export type Activity = {
	id: string,
	title: string,
	staticImage: string,
	timelineBlocks: TimelineBlock[],
	boardsRequired: number,
	description: string,
	loops: number,
};

export type AmplitudeSpectrum = {
	freqs_hz: number[],
	amplitude_x: number[],
	amplitude_y: number[],
	amplitude_xy: number[],
};

export type BalanceBoardCalibratedReading = {
	timestamp: string,
	mac_address: number,
	top_right: number,
	bottom_right: number,
	top_left: number,
	bottom_left: number,
};

export type BoardDisconnected = {
	macAddress: number,
};

export type CalibrationPosition = "top_left" | "top_right" | "bottom_left" | "bottom_right" | "center";

export type CalibrationPositionData = {
	position: CalibrationPosition,
	weight_kg: number,
	sensor_readings: BalanceBoardCalibratedReading,
};

export type CapturedCalibrationReading = {
	position: CalibrationPosition,
	reading: FrontendCalibrationReadingInput,
};

export type DeviceCalibrationData = {
	mac_address: number,
	calibration_weight_kg: number,
	positions: Partial<{ [key in CalibrationPosition]: CalibrationPositionData }>,
};

export type Duration = {
	secs: number,
	nanos: number,
};

export type FrontendBalanceBoardEvent = {
	event: "raw",
} & FrontendRawReadingData | {
	event: "processed",
} & FrontendProcessedReadingData;

/**  A live sensor reading while calibrating. */
export type FrontendCalibrationReading = {
	macAddress: number,
	timestamp: number,
	topLeft: number,
	topRight: number,
	bottomLeft: number,
	bottomRight: number,
	totalWeight: number,
};

/**  A reading the frontend captured at one calibration position and sends back. */
export type FrontendCalibrationReadingInput = {
	macAddress: number,
	/**  Unix milliseconds, as received in `FrontendCalibrationReading`. */
	timestamp: number,
	topLeft: number,
	topRight: number,
	bottomLeft: number,
	bottomRight: number,
};

export type FrontendProcessedReadingData = {
	macAddress: number,
	timestamp: number,
	vCopX: number | null,
	vCopY: number | null,
	confidenceEllipsePolygon: ([number, number])[] | null,
	convexHullPolygon: ([number, number])[] | null,
	amplitudeSpectrum: AmplitudeSpectrum | null,
	stabilityIndex: number | null,
	mlsi: number | null,
	apsi: number | null,
	vsi: number | null,
	dpsi: number | null,
};

export type FrontendRawReadingData = {
	macAddress: number,
	timestamp: number,
	weight: number,
	copX: number,
	copY: number,
};

export type GeneralSettings = {
	tcpConnectionStringRaw: string,
	tcpConnectionStringProcessed: string,
	tcpSendRawData: boolean,
	tcpSendProcessedData: boolean,
	lslStreamName: string,
	lslSourceId: string,
	lslSendRawData: boolean,
	lslSendProcessedData: boolean,
	storeFilesDefaultDirectory: string,
	storeRawSession: boolean,
	storeProcessedData: boolean,
	processingSettings: ProcessingSettings,
	isDemoMode: boolean,
};

export type InterpolationSetting = "Linear" | "Cubic" | "Polynomial";

export type LastSessionInformation = {
	user: User,
	sessionStats: SessionStats,
	fileLocation: string,
	activity: Activity | null,
};

export type NewBoard = {
	macAddress: number,
};

export type NintendoDevice = {
	id: string,
	name: string,
	macAddress: number,
	isConnected: boolean,
	lastConnected: string | null,
};

export type OngoingSessionActivityState = {
	currentBlockIndex: number,
	timeToNextBlockMs: number,
	loopNumber: number,
};

export type ProcessingSettings = {
	balanceBoardXSize: number,
	balanceBoardYSize: number,
	windowSizeMs: number,
	windowSlideMs: number,
	samplingRate: number,
	interpolation: InterpolationSetting,
	baselineWeight: number | null,
};

export type ReplayCompleted = null;

export type ReplayInformation = {
	user: User,
	core: SessionSettings,
	devices: SelectedBoard[],
	activity: Activity | null,
	filePath: string,
	hasOngoingSession: boolean,
};

export type SelectOption<T> = {
	label: string,
	value: T,
};

export type SelectedBoard = {
	name: string,
	macAddress: number,
};

export type SessionActivityChanged = null;

export type SessionActivityState = {
	activity: Activity,
	ongoingState: OngoingSessionActivityState | null,
};

export type SessionCompleted = null;

export type SessionInformation = {
	availableUsers: SelectOption<number>[],
	selectedBoards: SelectedBoard[],
	core: SessionSettings,
	activity: Activity | null,
	hasOngoingSession: boolean,
};

/**  The pipeline settings a user can change for a session or replay. */
export type SessionSettings = {
	selectedUser: number,
	activityId: string | null,
	lslEnabled: boolean,
	tcpEnabled: boolean,
	outputDirectory: string,
	windowSizeMs: number,
	windowSlideMs: number,
	samplingRate: number,
	interpolation: InterpolationSetting,
};

export type SessionStarted = null;

export type SessionStats = {
	boardSamplingRate: number,
	duration: Duration,
};

export type TimelineBlock = {
	title: string,
	id: string,
	duration: number,
};

export type User = {
	id: number,
	name: string,
	age: number | null,
	gender: string | null,
	height: number | null,
	heightMetric: string | null,
	/**  Always kilograms; this is the session baseline weight. */
	weight: number | null,
	/**  Display unit only (`kg` or `lb`). The frontend converts at its edge. */
	weightMetric: string | null,
	dominantHand: string | null,
	color: string | null,
	createdAt: string,
	updatedAt: string,
	isDefault: boolean,
};

/**
 *  Everything the users page shows, composed by the bridge from the users list and the
 *  session information so the page needs one request.
 */
export type UserPageInformation = {
	users: User[],
	selectedUserId: number,
	sessionDevices: SelectedBoard[],
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

