[package]
name = "the-balance-toolkitapp"
description = "A Toolkit to perform operations with a Nintendo Wii Balance Board"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
toolkit-core.workspace = true
anyhow.workspace = true
log.workspace = true
serde.workspace = true
tauri = { version = "2.11.5", features = ["unstable", "specta"] }
tauri-plugin-dialog = "2.7.3"
tokio.workspace = true
specta-typescript = "0.0.12"
specta = { version = "2.0.0-rc.25", features = ["derive", "chrono"] }
tauri-specta = { version = "2.0.0-rc.25", features = ["derive", "typescript"] }
chrono = { version = "0.4.45", features = ["serde"] }

[target.'cfg(target_os = "macos")'.dependencies]
objc2-app-kit = { version = "0.3.2", default-features = false, features = ["std", "NSWindow", "NSResponder"] }

[target.'cfg(target_os = "linux")'.dependencies]
gtk = "0.18"
