//! The desktop bridge: every Tauri command forwards one [`ToolkitCommand`] to the manager,
//! and every manager event becomes a typed Tauri event. Commands speak the wire types in
//! [`crate::frontend::dto`], never the core's own types.
//!
//! The TypeScript bindings for these commands and events (`apps/tauri/src/bindings.ts`) are
//! generated by `tauri-specta`: every debug launch rewrites them and the
//! `committed_bindings_are_current` test fails when they are stale.

use crate::frontend::dto::{
    Activity, CapturedCalibrationReading, DeviceCalibrationData, FrontendBalanceBoardEvent,
    FrontendCalibrationReading, GeneralSettings, LastSessionInformation, MacAddress,
    NintendoDevice, ReplayInformation, SessionActivityState, SessionInformation, SessionSettings,
    TimelineBlock, User, UserPageInformation,
};
use serde::{Deserialize, Serialize};
use specta::Type;
use specta_typescript::{Typescript, semantic};
use std::path::PathBuf;
use tauri::ipc::Channel;
use tauri::{AppHandle, State};
use tauri_specta::{Builder, ErrorHandlingMode, Event, collect_commands, collect_events};
use tokio::sync::mpsc::{Receiver, Sender};
use tokio::sync::{mpsc, oneshot};
use toolkit_core::actors::balance_board_actor::BoardAction;
use toolkit_core::actors::bluetooth_service::{BluetoothCommand, BluetoothPeripheral};
use toolkit_core::actors::toolkit_service::{ToolkitCommand, ToolkitResponse};

/// Where the generated TypeScript bindings live, relative to this crate.
const BINDINGS_PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../src/bindings.ts");

pub struct AppState {
    pub manager_tx: Sender<ToolkitCommand>,
}

/// Every command and event the frontend can use, in one place so the invoke handler and
/// the generated bindings cannot disagree.
fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        // The frontend treats a failed command like a rejected promise, as `invoke` did.
        .error_handling(ErrorHandlingMode::Throw)
        // MAC addresses are `u64`; they fit in a JavaScript number (48 bits).
        .dangerously_cast_bigints_to_number()
        // Floats are plain `number`s: serde_json would turn a NaN into `null`, but the
        // pipeline never emits one and the previous hand-written types assumed the same.
        .semantic_types(semantic::Configuration::empty().enable_lossless_floats())
        // Nothing serializes differently from how it deserializes, so one type per struct.
        .disable_serde_phases()
        .commands(collect_commands![
            settings_get_settings,
            settings_set_settings,
            user_page_information,
            user_select_user,
            user_create,
            user_update,
            user_delete,
            user_measure_weight,
            devices_get_selected_devices,
            devices_fetch_all_devices,
            devices_scan_without_timeout,
            devices_cancel_scan,
            devices_is_scanning,
            devices_select_device,
            devices_unselect_device,
            devices_update_device_name,
            devices_remove_device,
            devices_identify_device,
            devices_tare_device,
            devices_start_calibration_stream,
            devices_stop_calibration_stream,
            devices_submit_calibration,
            session_start_session,
            session_stop_session,
            session_information,
            session_update_session_configuration,
            session_activity_state,
            session_tare_devices,
            replay_start_replay,
            replay_stop_replay,
            replay_information,
            replay_update,
            replay_load_file,
            replay_clear_replay,
            replay_load_last_session_info,
            activity_get_available_time_blocks,
            activity_get_activities,
            activity_get_activity,
            activity_update_activity,
            activity_reset_activity_to_default,
        ])
        .events(collect_events![
            NewBoard,
            BoardDisconnected,
            SessionStarted,
            SessionCompleted,
            ReplayCompleted,
            SessionActivityChanged,
        ])
}

fn typescript() -> Typescript {
    Typescript::default().header(
        "// @ts-nocheck\n// Generated by tauri-specta from apps/tauri/src-tauri/src/frontend/tauri.rs. Do not edit.\n",
    )
}

pub fn initialize(manager_tx: Sender<ToolkitCommand>, manager_rx: Receiver<ToolkitResponse>) {
    let builder = specta_builder();

    #[cfg(debug_assertions)]
    if let Err(e) = builder.export(typescript(), BINDINGS_PATH) {
        log::error!("Failed to export the TypeScript bindings to {BINDINGS_PATH}: {e}");
    }

    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            forward_manager_events(app.handle().clone(), manager_rx);

            let monitor_dimensions = app
                .primary_monitor()
                .ok()
                .flatten()
                .map(|monitor| {
                    let size = monitor.size();
                    (size.width as f64, size.height as f64)
                })
                .or_else(|| {
                    app.available_monitors().ok().and_then(|monitors| {
                        monitors.into_iter().next().map(|monitor| {
                            let size = monitor.size();
                            (size.width as f64, size.height as f64)
                        })
                    })
                });

            let (initial_width, initial_height) = monitor_dimensions
                .map(|(width, height)| (width * 0.55, height * 0.6))
                .unwrap_or((800.0, 600.0));

            tauri::WebviewWindowBuilder::new(app.handle(), "main", tauri::WebviewUrl::default())
                .title("The Balance Toolkit")
                .resizable(true)
                .maximizable(true)
                .inner_size(initial_width, initial_height)
                .build()?;

            Ok(())
        })
        .manage(AppState { manager_tx })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

// --- EVENTS (manager -> frontend) ---

#[derive(Serialize, Deserialize, Debug, Clone, Type, Event)]
#[serde(rename_all = "camelCase")]
struct NewBoard {
    mac_address: MacAddress,
}

#[derive(Serialize, Deserialize, Debug, Clone, Type, Event)]
#[serde(rename_all = "camelCase")]
struct BoardDisconnected {
    mac_address: MacAddress,
}

#[derive(Serialize, Deserialize, Debug, Clone, Type, Event)]
struct SessionStarted;

#[derive(Serialize, Deserialize, Debug, Clone, Type, Event)]
struct SessionCompleted;

#[derive(Serialize, Deserialize, Debug, Clone, Type, Event)]
struct ReplayCompleted;

#[derive(Serialize, Deserialize, Debug, Clone, Type, Event)]
struct SessionActivityChanged;

/// Turns manager events into Tauri events. A failed emit (the windows are closing) is
/// logged rather than unwrapped: the release profile aborts on panic, which would take a
/// running recording down with it.
fn forward_manager_events(app: AppHandle, mut manager_rx: Receiver<ToolkitResponse>) {
    tokio::spawn(async move {
        while let Some(event) = manager_rx.recv().await {
            let result = match event {
                ToolkitResponse::NewDeviceFound(mac_address) => NewBoard { mac_address }.emit(&app),
                ToolkitResponse::BoardDisconnected(mac_address) => {
                    BoardDisconnected { mac_address }.emit(&app)
                }
                ToolkitResponse::SessionStarted => SessionStarted.emit(&app),
                ToolkitResponse::SessionCompleted => SessionCompleted.emit(&app),
                ToolkitResponse::ReplayCompleted => ReplayCompleted.emit(&app),
                ToolkitResponse::SessionActivityChanged => SessionActivityChanged.emit(&app),
            };
            if let Err(e) = result {
                log::warn!("Failed to forward a toolkit event to the frontend: {e}");
            }
        }
    });
}

// --- HELPERS ---

/// One request/response round trip to the manager.
async fn ask<T>(
    state: &State<'_, AppState>,
    build: impl FnOnce(oneshot::Sender<T>) -> ToolkitCommand,
) -> Result<T, String> {
    toolkit_core::request(&state.manager_tx, build)
        .await
        .map_err(|e| format!("{e:#}"))
}

/// A fire-and-forget command to the manager.
async fn tell(state: &State<'_, AppState>, command: ToolkitCommand) -> Result<(), String> {
    toolkit_core::send(&state.manager_tx, command)
        .await
        .map_err(|e| format!("{e:#}"))
}

fn map_all<A, B: From<A>>(items: Vec<A>) -> Vec<B> {
    items.into_iter().map(Into::into).collect()
}

/// Bridges an internal `mpsc` stream to a Tauri channel, mapping each item. Stops when
/// the frontend drops the channel.
fn forward_to_channel<In, Out>(
    channel: Channel<Out>,
    map: impl Fn(In) -> Out + Send + 'static,
) -> Sender<In>
where
    In: Send + 'static,
    Out: Send + Sync + Clone + Serialize + 'static,
{
    // Deep enough to ride out a webview stall of a few seconds at two boards x 100 Hz.
    // Producers skip samples for a full channel rather than dropping the frontend entirely.
    let (tx, mut rx) = mpsc::channel(2048);
    tokio::spawn(async move {
        while let Some(item) = rx.recv().await {
            if channel.send(map(item)).is_err() {
                log::debug!("Frontend channel closed");
                break;
            }
        }
    });
    tx
}

// --- SETTINGS ---

#[tauri::command]
#[specta::specta]
async fn settings_get_settings(state: State<'_, AppState>) -> Result<GeneralSettings, String> {
    ask(&state, |response| ToolkitCommand::GetSettings { response })
        .await
        .map(Into::into)
}

#[tauri::command]
#[specta::specta]
async fn settings_set_settings(
    settings: GeneralSettings,
    state: State<'_, AppState>,
) -> Result<(), String> {
    ask(&state, |response| ToolkitCommand::SaveSettings {
        settings: settings.into(),
        response,
    })
    .await
    .map(|_| ())
}

// --- USERS ---

#[tauri::command]
#[specta::specta]
async fn user_page_information(state: State<'_, AppState>) -> Result<UserPageInformation, String> {
    let users = ask(&state, |response| ToolkitCommand::GetUsers { response }).await?;
    let session = ask(&state, |response| ToolkitCommand::SessionInformation {
        response,
    })
    .await?;
    Ok(UserPageInformation::new(users, session))
}

#[tauri::command]
#[specta::specta]
async fn user_select_user(state: State<'_, AppState>, user_id: usize) -> Result<(), String> {
    tell(&state, ToolkitCommand::SelectUser { user_id }).await
}

#[tauri::command]
#[specta::specta]
async fn user_create(state: State<'_, AppState>) -> Result<User, String> {
    ask(&state, |response| ToolkitCommand::CreateUser { response })
        .await
        .map(|user| user.as_ref().clone().into())
}

#[tauri::command]
#[specta::specta]
async fn user_update(user: User, state: State<'_, AppState>) -> Result<(), String> {
    ask(&state, |response| ToolkitCommand::UpdateUser {
        user: user.into(),
        response,
    })
    .await
}

#[tauri::command]
#[specta::specta]
async fn user_delete(user_id: usize, state: State<'_, AppState>) -> Result<(), String> {
    ask(&state, |response| ToolkitCommand::DeleteUser {
        user_id,
        response,
    })
    .await
}

#[tauri::command]
#[specta::specta]
async fn user_measure_weight(
    state: State<'_, AppState>,
    channel: Channel<f64>,
    mac_address: MacAddress,
) -> Result<(), String> {
    let frontend_channel = forward_to_channel(channel, |weight| weight);
    tell(
        &state,
        ToolkitCommand::MeasureWeight {
            frontend_channel,
            mac_address,
        },
    )
    .await
}

// --- DEVICES ---

#[tauri::command]
#[specta::specta]
async fn devices_fetch_all_devices(
    state: State<'_, AppState>,
) -> Result<Vec<NintendoDevice>, String> {
    ask(&state, |response| ToolkitCommand::GetBoardsSystemView {
        response,
    })
    .await
    .map(map_all)
}

#[tauri::command]
#[specta::specta]
async fn devices_scan_without_timeout(state: State<'_, AppState>) -> Result<(), String> {
    // Flow: First we connect via bluetooth, then we connect via HID.
    let (new_bluetooth_tx, mut new_bluetooth_rx) = mpsc::channel::<BluetoothPeripheral>(10);
    let manager_tx = state.manager_tx.clone();
    tokio::spawn(async move {
        while let Some(device) = new_bluetooth_rx.recv().await {
            let command = ToolkitCommand::Connect {
                mac_address: device.mac_address,
            };
            if manager_tx.send(command).await.is_err() {
                log::warn!("The toolkit manager stopped; ending the scan forwarder");
                break;
            }
        }
    });

    ask(&state, |response| {
        ToolkitCommand::BluetoothAction(BluetoothCommand::StartScanAndPair {
            response_stream: new_bluetooth_tx,
            response,
        })
    })
    .await
}

#[tauri::command]
#[specta::specta]
async fn devices_cancel_scan(state: State<'_, AppState>) -> Result<(), String> {
    ask(&state, |response| {
        ToolkitCommand::BluetoothAction(BluetoothCommand::StopScan { response })
    })
    .await
}

#[tauri::command]
#[specta::specta]
async fn devices_is_scanning(state: State<'_, AppState>) -> Result<bool, String> {
    ask(&state, |response| {
        ToolkitCommand::BluetoothAction(BluetoothCommand::IsScanning { response })
    })
    .await
}

#[tauri::command]
#[specta::specta]
async fn devices_remove_device(
    mac_address: MacAddress,
    state: State<'_, AppState>,
) -> Result<(), String> {
    tell(
        &state,
        ToolkitCommand::BluetoothAction(BluetoothCommand::RemoveDevice { mac_address }),
    )
    .await
}

#[tauri::command]
#[specta::specta]
async fn devices_update_device_name(
    mac_address: MacAddress,
    device_name: String,
    state: State<'_, AppState>,
) -> Result<(), String> {
    tell(
        &state,
        ToolkitCommand::UpdateBoardName {
            mac_address,
            device_name,
        },
    )
    .await
}

#[tauri::command]
#[specta::specta]
async fn devices_identify_device(
    mac_address: MacAddress,
    state: State<'_, AppState>,
) -> Result<(), String> {
    tell(&state, ToolkitCommand::IdentifyBoard { mac_address }).await
}

#[tauri::command]
#[specta::specta]
async fn devices_tare_device(
    mac_address: MacAddress,
    state: State<'_, AppState>,
) -> Result<(), String> {
    tell(
        &state,
        ToolkitCommand::BoardAction {
            mac_address,
            action: BoardAction::Tare,
        },
    )
    .await
}

#[tauri::command]
#[specta::specta]
async fn devices_start_calibration_stream(
    mac_address: MacAddress,
    calibration_channel: Channel<FrontendCalibrationReading>,
    state: State<'_, AppState>,
) -> Result<(), String> {
    let frontend_channel =
        forward_to_channel(calibration_channel, FrontendCalibrationReading::from);
    tell(
        &state,
        ToolkitCommand::StartCalibrationStream {
            mac_address,
            frontend_channel,
        },
    )
    .await
}

#[tauri::command]
#[specta::specta]
async fn devices_stop_calibration_stream(
    mac_address: MacAddress,
    state: State<'_, AppState>,
) -> Result<(), String> {
    tell(
        &state,
        ToolkitCommand::StopCalibrationStream { mac_address },
    )
    .await
}

#[tauri::command]
#[specta::specta]
async fn devices_submit_calibration(
    mac_address: MacAddress,
    weight_kg: f64,
    readings: Vec<CapturedCalibrationReading>,
    state: State<'_, AppState>,
) -> Result<DeviceCalibrationData, String> {
    ask(&state, |response| ToolkitCommand::SubmitCalibration {
        mac_address,
        weight_kg,
        readings: map_all(readings),
        response,
    })
    .await?
    .map(Into::into)
}

#[tauri::command]
#[specta::specta]
async fn devices_select_device(
    mac_address: MacAddress,
    state: State<'_, AppState>,
) -> Result<(), String> {
    tell(
        &state,
        ToolkitCommand::SelectBoardForSession { mac_address },
    )
    .await
}

#[tauri::command]
#[specta::specta]
async fn devices_unselect_device(
    mac_address: MacAddress,
    state: State<'_, AppState>,
) -> Result<(), String> {
    tell(
        &state,
        ToolkitCommand::UnselectBoardForSession { mac_address },
    )
    .await
}

#[tauri::command]
#[specta::specta]
async fn devices_get_selected_devices(
    state: State<'_, AppState>,
) -> Result<Vec<MacAddress>, String> {
    ask(&state, |response| {
        ToolkitCommand::SelectedBoardsForSession { response }
    })
    .await
}

// --- SESSION ---

#[tauri::command]
#[specta::specta]
async fn session_information(state: State<'_, AppState>) -> Result<SessionInformation, String> {
    ask(&state, |response| ToolkitCommand::SessionInformation {
        response,
    })
    .await
    .map(Into::into)
}

#[tauri::command]
#[specta::specta]
async fn session_update_session_configuration(
    configuration: SessionSettings,
    state: State<'_, AppState>,
) -> Result<(), String> {
    ask(&state, |response| {
        ToolkitCommand::UpdateSessionInformation {
            configuration: configuration.into(),
            response,
        }
    })
    .await
}

/// Everything the activity popup needs: the activity, the current block and the time
/// until the next one.
#[tauri::command]
#[specta::specta]
async fn session_activity_state(
    state: State<'_, AppState>,
) -> Result<Option<SessionActivityState>, String> {
    ask(&state, |response| ToolkitCommand::SessionActivityState {
        response,
    })
    .await
    .map(|state| state.map(Into::into))
}

#[tauri::command]
#[specta::specta]
async fn session_tare_devices(state: State<'_, AppState>) -> Result<(), String> {
    ask(&state, |response| ToolkitCommand::SessionTareDevices {
        response,
    })
    .await
}

#[tauri::command]
#[specta::specta]
async fn session_start_session(
    state: State<'_, AppState>,
    session_channel: Channel<FrontendBalanceBoardEvent>,
) -> Result<(), String> {
    let frontend_channel = forward_to_channel(session_channel, FrontendBalanceBoardEvent::from);
    ask(&state, |response| ToolkitCommand::StartSession {
        frontend_channel,
        response,
    })
    .await
}

#[tauri::command]
#[specta::specta]
async fn session_stop_session(state: State<'_, AppState>) -> Result<(), String> {
    ask(&state, |response| ToolkitCommand::StopSession { response }).await
}

// --- REPLAY ---

#[tauri::command]
#[specta::specta]
async fn replay_start_replay(
    state: State<'_, AppState>,
    session_channel: Channel<FrontendBalanceBoardEvent>,
) -> Result<(), String> {
    let frontend_channel = forward_to_channel(session_channel, FrontendBalanceBoardEvent::from);
    ask(&state, |response| ToolkitCommand::StartReplay {
        frontend_channel,
        response,
    })
    .await
}

#[tauri::command]
#[specta::specta]
async fn replay_stop_replay(state: State<'_, AppState>) -> Result<(), String> {
    ask(&state, |response| ToolkitCommand::StopReplay { response }).await
}

#[tauri::command]
#[specta::specta]
async fn replay_information(
    state: State<'_, AppState>,
) -> Result<Option<ReplayInformation>, String> {
    ask(&state, |response| ToolkitCommand::ReplayInformation {
        response,
    })
    .await
    .map(|replay| replay.map(Into::into))
}

#[tauri::command]
#[specta::specta]
async fn replay_update(
    configuration: SessionSettings,
    state: State<'_, AppState>,
) -> Result<(), String> {
    ask(&state, |response| ToolkitCommand::UpdateReplayInformation {
        configuration: configuration.into(),
        response,
    })
    .await
}

#[tauri::command]
#[specta::specta]
async fn replay_load_file(file_path: PathBuf, state: State<'_, AppState>) -> Result<(), String> {
    ask(&state, |response| ToolkitCommand::LoadReplayFile {
        file_path,
        response,
    })
    .await
}

#[tauri::command]
#[specta::specta]
async fn replay_clear_replay(state: State<'_, AppState>) -> Result<(), String> {
    ask(&state, |response| ToolkitCommand::ClearReplay { response }).await
}

#[tauri::command]
#[specta::specta]
async fn replay_load_last_session_info(
    state: State<'_, AppState>,
) -> Result<Option<LastSessionInformation>, String> {
    ask(&state, |response| ToolkitCommand::LastSessionInformation {
        response,
    })
    .await
    .map(|info| info.map(Into::into))
}

// --- ACTIVITIES ---

#[tauri::command]
#[specta::specta]
async fn activity_get_available_time_blocks(
    state: State<'_, AppState>,
) -> Result<Vec<TimelineBlock>, String> {
    ask(&state, |response| ToolkitCommand::GetAvailableTimeBlocks {
        response,
    })
    .await
    .map(map_all)
}

#[tauri::command]
#[specta::specta]
async fn activity_get_activities(state: State<'_, AppState>) -> Result<Vec<Activity>, String> {
    ask(&state, |response| ToolkitCommand::GetActivities {
        response,
    })
    .await
    .map(map_all)
}

#[tauri::command]
#[specta::specta]
async fn activity_get_activity(
    activity_id: String,
    state: State<'_, AppState>,
) -> Result<Activity, String> {
    ask(&state, |response| ToolkitCommand::GetActivity {
        activity_id,
        response,
    })
    .await
    .map(Into::into)
}

#[tauri::command]
#[specta::specta]
async fn activity_update_activity(
    activity: Activity,
    state: State<'_, AppState>,
) -> Result<(), String> {
    ask(&state, |response| ToolkitCommand::UpdateActivity {
        activity: activity.into(),
        response: Some(response),
    })
    .await
}

#[tauri::command]
#[specta::specta]
async fn activity_reset_activity_to_default(
    activity_id: String,
    state: State<'_, AppState>,
) -> Result<Activity, String> {
    ask(&state, |response| ToolkitCommand::ResetActivityToDefault {
        activity_id,
        response,
    })
    .await
    .map(Into::into)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn export_to_string() -> String {
        let dir = std::env::temp_dir().join(format!("tbt-bindings-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("bindings.ts");
        specta_builder().export(typescript(), &path).unwrap();
        let bindings = std::fs::read_to_string(&path).unwrap();
        let _ = std::fs::remove_dir_all(dir);
        bindings
    }

    /// Regenerates `apps/tauri/src/bindings.ts`: `mise run gen:bindings`.
    #[test]
    #[ignore = "writes the committed bindings; run explicitly"]
    fn export_bindings() {
        std::fs::write(BINDINGS_PATH, export_to_string()).unwrap();
    }

    #[test]
    fn committed_bindings_are_current() {
        let committed = std::fs::read_to_string(BINDINGS_PATH).unwrap_or_default();
        assert!(
            committed == export_to_string(),
            "apps/tauri/src/bindings.ts is stale; run `mise run gen:bindings`"
        );
    }
}
